- hosts: all
  # Update system packages
  pre_tasks:
    - apt:
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"
  roles:
    # Install docker
    - role: geerlingguy.docker
      become: true
      docker_users:
        - vagrant

  tasks:
    - name: Get latest version of lando
      uri:
        url: https://api.github.com/repos/lando/lando/releases/latest
        return_content: true
      register: lando_latest

    - name: "get .deb package URL for {{ lando_latest.json.tag_name }}"
      set_fact:
        lando_deb_url: "{{ item.browser_download_url }}"
      loop: "{{ lando_latest.json.assets }}"
      when: item.name | regex_search("^lando-v.*\.deb$")

    - name: Install lando .deb package
      become: true
      apt:
        deb: "{{ lando_deb_url }}"

    - name: Clone the va.gov CMS repo
      ansible.builtin.git:
        repo: https://github.com/{{ gh_username }}/va.gov-cms.git
        dest: ~/va.gov-cms
        accept_hostkey: yes

    # See https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc for more information.
    - name: Increase file change watch limit
      become: true
      sysctl:
        name: fs.inotify.max_user_watches
        value: '524288'

    - name: Start docker
      command: systemctl start docker
      become: true
      register: docker_output

